# Configuration for the GoatTrails route generator

# The desired length of the routes in kilometers.
target_distance_km = 20.0

# The number of iterations for the inner route-finding algorithm.
# A higher number may produce better routes but will take longer.
algorithm_iterations = 1000

# The number of routes to generate in the outer loop (X).
route_candidates_to_generate = 1

# The number of top routes to display on the map (Y).
top_routes_to_display = 3

# Optional fixed starting point for route generation.
# If commented out, a random parking location will be used.
[start_point]
lat = 51.774716
lon = -1.311914

# Penalties for different types of ways. Higher values make the way less desirable.
# The algorithm will tend to avoid ways with high penalties.
[way_penalties]
default = 1.0
motorway = 500.0
primary = 20.0
trunk = 50.0
tertiary = 1.5
residential = 1.2
unclassified = 1.1
